# Generated by Django 4.1.4 on 2024-02-06 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('announcement_title', models.CharField(max_length=255)),
                ('announcement_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('incident_image', models.ImageField(blank=True, null=True, upload_to='incident_images/')),
                ('location', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255, unique=True)),
                ('resource_image', models.ImageField(blank=True, null=True, upload_to='resource_images/')),
                ('resource_type', models.CharField(choices=[('Sports', 'Sports'), ('Learning', 'Learning'), ('Entertainment', 'Entertainment')], max_length=255)),
                ('resource_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Maintenance', 'Maintenance')], max_length=100)),
                ('resource_capacity', models.IntegerField()),
                ('booking_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('room_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('number_access_card', models.PositiveIntegerField()),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('ELECTRIC', 'ELECTRIC'), ('WATER', 'WATER'), ('WIFI', 'WIFI'), ('RENTAL', 'RENTAL'), ('MAINTAINENCE', 'MAINTAINENCE')], max_length=100)),
                ('recipient_name', models.TextField()),
                ('total_payment', models.FloatField()),
                ('payment_amount', models.FloatField()),
                ('account_number', models.TextField()),
                ('card_type', models.TextField()),
                ('remark', models.TextField()),
                ('payment_date', models.DateField(null=True)),
                ('transaction_status', models.CharField(default='Pending', max_length=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=60, null=True)),
                ('date_string', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_fk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resource', to_field='resource_id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users', to_field='user_name')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
